version: "3.8"
services:
  auth:
    build: ./auth
    container_name: auth-container
    depends_on:
      - auth-db
    develop:
      watch:
        - action: sync
          path: ./auth
          target: /auth
          ignore:
            - node_modules/
        - action: rebuild
          path: ./auth/package.json
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://auth-db:27017/userdb
  product:
    build: ./product
    container_name: product-container
    depends_on:
      - product-db
    develop:
      watch:
        - action: sync
          path: ./product
          target: /product
          ignore:
            - node_modules/
        - action: rebuild
          path: ./product/package.json
    ports:
      - 4000:4000
    environment:
      MONGO_URL: mongodb://product-db:27017/productdb
  cart:
    build: ./cart
    container_name: cart-container
    depends_on:
      - cart-db
    develop:
      watch:
        - action: sync
          path: ./cart
          target: /cart
          ignore:
            - node_modules/
        - action: rebuild
          path: ./cart/package.json
    ports:
      - 5000:5000
    environment:
      MONGO_URL: mongodb://cart-db:27017/productdb
  client:
    build: ./client
    develop:
      watch:
        - action: sync
          path: ./client
          target: /client
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json
    container_name: client-container
    ports:
      - 8080:8080
  auth-db:
    image: mongo
    restart: always
    ports:
      - 3001:27017
    volumes:
      - user_db:/data/db
  cart-db:
    image: mongo
    restart: always
    ports: 
      - 5001:27017
    volumes:
      - cart_db:/data/db
  product-db:
    image: mongo
    restart: always
    ports:
      - 4001:27017
    volumes:
      - product_db:/data/db
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672

volumes:
  user_db:
    name: user_data
  product_db:
    name: product_data
  cart_db:
    name: cart_data
