apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: ajmalj/ecom-cart
          ports:
            - containerPort: 5000
          env:
            - name : MONGO_URL
              value: mongodb://cart-db:27017/productdb
---
apiVersion: v1
kind: Service
metadata:
  name: cart-srv
spec:
  selector:
    app: cart
  ports:
    - name: cart
      protocol: TCP
      port: 5000
      targetPort: 5000
